# Generated by Django 5.1.4 on 2025-01-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_address_alter_organisation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='location',
        ),
    ]
